"""LLM prompt templates for all agent nodes that use language models."""

from app.agents.prompts.templates import (
    DECISION_SYSTEM_PROMPT,
    DECISION_USER_TEMPLATE,
    MEMORY_RETRIEVAL_TEMPLATE,
    NEWS_SENTIMENT_SYSTEM_PROMPT,
    NEWS_SENTIMENT_USER_TEMPLATE,
    REFLECTION_SYSTEM_PROMPT,
    REFLECTION_USER_TEMPLATE,
)

__all__ = [
    "DECISION_SYSTEM_PROMPT",
    "DECISION_USER_TEMPLATE",
    "MEMORY_RETRIEVAL_TEMPLATE",
    "NEWS_SENTIMENT_SYSTEM_PROMPT",
    "NEWS_SENTIMENT_USER_TEMPLATE",
    "REFLECTION_SYSTEM_PROMPT",
    "REFLECTION_USER_TEMPLATE",
]
